---
- name: Check current node_exporter version
  failed_when: false
  changed_when: false
  register: prometheus_node_exporter_bin_stat
  ansible.builtin.stat:
    path: "{{ prometheus_node_exporter_bin_path }}"

- name: Check current node_exporter version
  become: true
  when:
    - prometheus_node_exporter_bin_stat.stat.exists
  failed_when: false
  changed_when: false
  register: prometheus_node_exporter_version_check
  ansible.builtin.command:
    cmd: "{{ prometheus_node_exporter_bin_path }} --version"

- name: Stop node_exporter
  become: true
  when:
    - prometheus_node_exporter_bin_stat.stat.exists
  ignore_errors: true
  ansible.builtin.service:
    name: "{{ prometheus_node_exporter_name }}"
    state: stopped
    enabled: false

- name: Download and decompress node_exporter into temporary location
  when:
    not prometheus_node_exporter_bin_stat.stat.exists
    or
    prometheus_node_exporter_version_check.stdout is not defined
    or
    prometheus_node_exporter_version not in prometheus_node_exporter_version_check.stdout
  ansible.builtin.unarchive:
    src: "{{ prometheus_node_exporter_download_url | replace(' ', '') }}"
    dest: /tmp
    remote_src: true

- name: Move node_exporter binary into place
  become: true
  when:
    not prometheus_node_exporter_bin_stat.stat.exists
    or
    prometheus_node_exporter_version_check.stdout is not defined
    or
    prometheus_node_exporter_version not in prometheus_node_exporter_version_check.stdout
  ansible.builtin.copy:
    src: /tmp/{{ prometheus_node_exporter_name }}-{{ prometheus_node_exporter_version }}.linux-{{ prometheus_node_exporter_arch }}/{{ prometheus_node_exporter_name }}
    dest: "{{ prometheus_node_exporter_bin_path }}"
    mode: "0755"
    remote_src: true

- name: Create node_exporter user
  become: true
  ansible.builtin.user:
    name: "{{ prometheus_node_exporter_name }}"
    shell: /sbin/nologin
    state: present

- name: Create node_exporter systemd unit file
  become: true
  when: ansible_service_mgr == "systemd"
  ansible.builtin.template:
    src: exporter.service.j2
    dest: /etc/systemd/system/{{ prometheus_node_exporter_name }}.service
    mode: "0644"
    owner: root
    group: root

- name: Create node_exporter sysv init file
  become: true
  when: ansible_service_mgr == "sysvinit"
  ansible.builtin.template:
    src: exporter.j2
    dest: /etc/init.d/{{ prometheus_node_exporter_name }}
    mode: "0644"
    owner: root
    group: root

# - name: "Sysvinit enable"
#   when: ansible_service_mgr == "sysvinit"
#   ansible.builtin.command:
#     cmd: "chkconfig {{ prometheus_node_exporter_name }} on"

- name: Systemd daemon-reload
  become: true
  when: ansible_service_mgr == "systemd"
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure node_exporter is started
  become: true
  ansible.builtin.service:
    name: "{{ prometheus_node_exporter_name }}"
    enabled: true
    state: started
