---
- name: stop node_exporter container
  community.docker.docker_container:
    name: node_exporter
    state: stopped
  ignore_errors: true

- name: remove node_exporter container
  community.docker.docker_container:
    name: node_exporter
    state: absent
  ignore_errors: true
